services:
  weather-ticker:
    build: .
    image: wcp-widget-weather-ticker
    container_name: wcp-widget-weather-ticker
    ports:
      - "3739:3739"
    environment:
      - CONTAINER_NAME=wcp-widget-weather-ticker
    restart: unless-stopped
    volumes:
      - weather_config:/app/data
      - ./published:/app/published

volumes:
  weather_config:
